COMPONENT = TreeRoutingC

# msg size up to 127
MSG_SIZE = 29
# channels from 11 to 26
CFLAGS+=-DCC2420_DEF_CHANNEL=11
# transmission power from 1 to 31
CFLAGS+=-DCC2420_DEF_RFPOWER=27

include $(MAKERULES)

